title: ECE 196 Group 8 Final Project
description: Final project for ECE 196

locale: "en-US"
minimal_mistakes_skin: "dark"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

nav:
  - title: "Home"
    url: /
  - title: "Team"
    url: /team/
  - title: "Problem"
    url: /problem/
