theme: minimal-mistakes-jekyll

title: ECE 196 Group 8 Final Project
description: Final project for ECE 196

locale: "en-US"
minimal_mistakes_skin: "dark"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache
